version: '3'
services:
  api:
    container_name: api
    build: .
    ports:
      - '80:3000'
    external_links:
      - mongo
    depends_on:
      - mongo
    
  mongo:
    container_name: mongo
    image: mongo:5.0.7
    ports:
      - "27017:27017"