version: '3'
services:
  api:
    container_name: api
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./covid-travel-api:/usr/src/app
    external_links:
      - mongo
    depends_on:
      - mongo
    restart: always
    
  mongo:
    container_name: mongo
    image: mongo:5.0.7
    ports:
      - "27017:27017"
    expose:
      - "27017"